#!/bin/bash

O="${1:?BAD_ORG}"

BASE=$(dirname "$(realpath "$0")")
# shellcheck source-path=$BASE
source "${BASE}/utils/xecho.sh"

xecho "3: 􀇿  CLONING ALL PUBLIC ACTIVE ORIGIN REPOS"
xecho "4: ⌜${O}⌟"
xecho "5: $PWD/${O}-org"

sleep 3

if [ "${PWD##*/}-org" != "${O}-org" ]; then
  ! [ -d "${O}-org" ] && mkdir "${O}-org"
  cd "${O}-org" || exit
fi

while read -r X; do
  read -r N D L < <(awk -F, '{print $1,$2,$3}' <<< "$X")
  [ "$L" != "" ] && L="_${L::1}${L:(-4)}"
  D=$(date -d "$D" +%y%m)
  U="git@github.com:${O}/${N}.git"
  P="${N,,}${L,,}_${D}"

  xecho "6: $N" "$D" "${PWD/${HOME}/··}/" "${P}"

  [ -d "$P" ] || git clone --depth 1 "$U" "$P"
done < <(gh repo list \
  --limit 300 \
  --source \
  --no-archived \
  --json 'name,primaryLanguage,updatedAt' \
  --jq '.[] | .name+","+.updatedAt+","+.primaryLanguage.name' \
  "$O")

# vim: ft=bash
